[versions]
jdk = "17"
agp = "8.7.2"
android-compileSdk = "35"
android-minSdk = "24"
android-targetSdk = "35"
kotlin = "2.0.21"
google-services = "4.4.2"
jetbrainsKotlinJvm = "1.9.24"
compose-multiplatform = "1.7.0"
kotlinx-coroutines = "1.9.0"
kotlinx-datetime = "0.6.1"
kotlinx-serialization = "1.7.3"
androidx-appcompat = "1.7.0"
androidx-activity = "1.9.3"
androidx-browser = "1.8.0"
androidx-compose-animation = "1.7.5"
androidx-compose-foundation = "1.7.5"
androidx-compose-runtime = "1.7.5"
androidx-compose-ui = "1.7.5"
androidx-compose-ui-tooling-preview-desktop = "1.7.5"
androidx-compose-material = "1.7.5"
androidx-compose-material3 = "1.3.1"
androidx-core-ktx = "1.15.0"
androidx-datastore = "1.1.1"
androidx-datastore-core-okio-jvm = "1.1.1"
androidx-lifecycle = "2.8.7"
androidx-lifecycle-viewmodel = "2.8.7"
androidx-navigation = "2.8.4"
androidx-test-ext = "1.2.1"
androidx-work = "2.10.0"
jetbrains-androidx-navigation-compose = "2.8.0-alpha10"
jetbrains-androidx-lifecycle-viewmodel-compose = "2.8.2"
jetbrains-androidx-core-bundle = "1.0.1"
coil = "2.7.0"
coil3 = "3.0.0-alpha08"
junit = "4.13.2"
koin = "4.0.0"
koin-compose = "4.0.0"
constraintlayout-compose-multiplatform = "0.4.0"
napier = "2.7.1"
google-firebase-kmm = "2.1.0"
voyager = "1.1.0-beta02"
uiDesktop = "1.7.0"
buildConfig = "4.2.0"
accompanist = "0.36.0"
notifier = "1.3.0"
tests = "1.6.1"
tests-junit = "1.2.1"
turbine = "1.2.0"

[libraries]
test-core = { module = "androidx.test:core", version.ref = "tests" }
test-runner = { module = "androidx.test:runner", version.ref = "tests" }
test-rules = { module = "androidx.test:rules", version.ref = "tests" }
test-junit = { module = "androidx.test.ext:junit", version.ref = "tests-junit" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-appcompat-resources = { module = "androidx.appcompat:appcompat-resources", version.ref = "androidx-appcompat" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-compose-animation = { module = "androidx.compose.animation:animation", version.ref = "androidx-compose-animation" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "androidx-compose-foundation" }
androidx-compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "androidx-compose-foundation" }
androidx-compose-material-ripple = { module = "androidx.compose.material:material-ripple", version.ref = "androidx-compose-material" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "androidx-compose-material" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidx-compose-material3" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "androidx-compose-runtime" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose-ui" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose-ui" }
androidx-compose-ui-text = { module = "androidx.compose.ui:ui-text", version.ref = "androidx-compose-ui" }
androidx-compose-ui-tooling-preview-android = { module = "androidx.compose.ui:ui-tooling-preview-android", version.ref = "androidx-compose-ui" }
androidx-compose-ui-tooling-preview-desktop = { module = "androidx.compose.ui:ui-tooling-preview-desktop", version.ref = "androidx-compose-ui-tooling-preview-desktop" }
androidx-compose-ui-util = { module = "androidx.compose.ui:ui-util", version.ref = "androidx-compose-ui" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "androidx-browser" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-ktx" }
androidx-datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "androidx-datastore" }
androidx-datastore-core-okio-jvm = { module = "androidx.datastore:datastore-core-okio-jvm", version.ref = "androidx-datastore-core-okio-jvm" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore" }
androidx-datastore-preferences-core = { module = "androidx.datastore:datastore-preferences-core", version.ref = "androidx-datastore" }
androidx-lifecycle-common = { module = "androidx.lifecycle:lifecycle-common", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-lifecycle-viewmodel" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "androidx-lifecycle" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
androidx-test-ext-junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "androidx-test-ext" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work" }
jetbrains-androidx-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "jetbrains-androidx-navigation-compose" }
jetbrains-androidx-lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "jetbrains-androidx-lifecycle-viewmodel-compose" }
jetbrains-androidx-core-bundle = { module = "org.jetbrains.androidx.core:core-bundle", version.ref = "jetbrains-androidx-core-bundle" }
jetbrains-androidx-lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "jetbrains-androidx-lifecycle-viewmodel-compose" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coil3-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil3" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-androidx-workmanager = { module = "io.insert-koin:koin-androidx-workmanager", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin-compose" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin-compose" }
constraintlayout-compose-multiplatform = { module = "tech.annexflow.compose:constraintlayout-compose-multiplatform", version.ref = "constraintlayout-compose-multiplatform" }
google-firebase-common = { module = "dev.gitlive:firebase-common", version.ref = "google-firebase-kmm" }
google-firebase-auth = { module = "dev.gitlive:firebase-auth", version.ref = "google-firebase-kmm" }
google-firebase-database = { module = "dev.gitlive:firebase-database", version.ref = "google-firebase-kmm" }
google-firebase-messaging = { module = "dev.gitlive:firebase-messaging", version.ref = "google-firebase-kmm" }
napier = { module = "io.github.aakira:napier", version.ref = "napier" }
voyager-navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyager" }
voyager-screenModel = { module = "cafe.adriel.voyager:voyager-screenmodel", version.ref = "voyager" }
voyager-bottomSheetNavigator = { module = "cafe.adriel.voyager:voyager-bottom-sheet-navigator", version.ref = "voyager" }
voyager-tabNavigator = { module = "cafe.adriel.voyager:voyager-tab-navigator", version.ref = "voyager" }
voyager-transitions = { module = "cafe.adriel.voyager:voyager-transitions", version.ref = "voyager" }
voyager-koin = { module = "cafe.adriel.voyager:voyager-koin", version.ref = "voyager" }
androidx-ui-desktop = { group = "androidx.compose.ui", name = "ui-desktop", version.ref = "uiDesktop" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
notifier = { module = "io.github.mirzemehdi:kmpnotifier", version.ref = "notifier" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

[bundles]
kotlinx-coroutines-common = [
    "kotlinx-coroutines-core"
]
kotlinx-datetime-common = [
    "kotlinx-datetime"
]
kotlinx-serialization-common = [
    "kotlinx-serialization-json"
]
jetbrains-androidx-navigation-compose-common = [
    "jetbrains-androidx-navigation-compose"
]
jetbrains-androidx-lifecycle-viewmodel-compose-common = [
    "jetbrains-androidx-lifecycle-viewmodel-compose"
]
jetbrains-androidx-core-bundle-common = [
    "jetbrains-androidx-core-bundle"
]
datastore-common = [
    "androidx-datastore-core",
    "androidx-datastore-preferences-core"
]
lifecycle-common = [
    "androidx-lifecycle-common",
]
koin-common = [
    "koin-compose",
    "koin-compose-viewmodel"
]
coil-common = [
    "coil3-compose"
]
constraintlayout-common = [
    "constraintlayout-compose-multiplatform"
]
kotlinx-coroutines-android = [
    "kotlinx-coroutines-android"
]
activity-android = [
    "androidx-activity-compose"
]
appcompat-android = [
    "androidx-appcompat",
    "androidx-appcompat-resources"
]
compose-android = [
    "androidx-compose-animation",
    "androidx-compose-foundation",
    "androidx-compose-foundation-layout",
    #"androidx-compose-material-ripple",
    "androidx-compose-material-icons-extended",
    "androidx-compose-material3",
    "androidx-compose-runtime",
    "androidx-compose-ui",
    "androidx-compose-ui-tooling",
    "androidx-compose-ui-tooling-preview-android",
    "androidx-compose-ui-util"
]
core-android = [
    "androidx-core-ktx"
]
datastore-android = [
    "androidx-datastore-preferences"
]
lifecycle-android = [
    "androidx-lifecycle-runtime-compose",
    "androidx-lifecycle-process"
]
navigation-android = [
    "androidx-navigation-compose"
]
test-ext-junit-android = [
    "androidx-test-ext-junit-ktx"
]
work-android = [
    "androidx-work-runtime-ktx"
]
coil-android = [
    "coil-compose"
]
junit-android = [
    "junit"
]
kotlinx-coroutines-desktop = [
    "kotlinx-coroutines-swing"
]
compose-desktop = [
    "androidx-compose-ui-tooling-preview-desktop"
]
datastore-desktop = [
    "androidx-datastore-core-okio-jvm"
]
voyager = [
    "voyager-navigator",
    "voyager-screenModel",
    "voyager-bottomSheetNavigator",
    "voyager-tabNavigator",
    "voyager-transitions",
    "voyager-koin"
]
koin-android = [
    "koin-android",
    "koin-androidx-compose",
    "koin-androidx-workmanager"
]
google-firebase = [
    "google-firebase-auth",
    "google-firebase-database",
    "google-firebase-messaging"
]
tests = [
    "kotlin-test",
    "test-core",
    "test-rules",
    "test-runner",
    "test-junit"
]

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinCocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
jetbrainsKotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
androidx-navigation-safeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "androidx-navigation" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildConfig" }