name: Android Release

on:
  push:
    tags:
      - '*-android'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup-gradle
        with:
          gradle-cache-encryption-key: ${{ secrets.GRADLE_CACHE_ENCRYPTION_KEY }}

      - name: Configure Keystore
        run: |
          echo '${{ secrets.KEYSTORE_FILE }}' > release.keystore.asc
          gpg -d --passphrase '${{ secrets.KEYSTORE_PASSPHRASE }}' --batch release.keystore.asc > shared/release.keystore

      - name: Create Firebase config
        run: |
          echo '
          firebaseAndroidApiKey="${{ secrets.FIREBASE_ANDROID_API_KEY }}"
          firebaseIosApiKey="${{ secrets.FIREBASE_IOS_API_KEY }}"
          firebaseGcmSenderId="${{ secrets.FIREBASE_GCM_SENDER_ID }}"
          firebaseApplicationId="${{ secrets.FIREBASE_APPLICATION_ID }}"
          firebaseStorageBucket="${{ secrets.FIREBASE_STORAGE_BUCKET }}"
          firebaseProjectId="${{ secrets.FIREBASE_PROJECT_ID }}"
          firebaseDatabaseUrl="${{ secrets.FIREBASE_DATABASE_URL }}"
          bloodlineReleaseKeystore=./release.keystore
          bloodlineReleasePassword=${{ secrets.KEYSTORE_KEY_PASSWORD }}
          bloodlineReleaseAlias=${{ secrets.KEYSTORE_KEY_ALIAS }}
          googleAndroidClientId="${{ secrets.GOOGLE_ANDROID_CLIENT_ID }}"
          googleIosClientId="${{ secrets.GOOGLE_IOS_CLIENT_ID }}"
          googleClientId="${{ secrets.GOOGLE_CLIENT_ID }}"
          googleClientSecret="${{ secrets.GOOGLE_CLIENT_SECRET }}"
          facebookClientId="${{ secrets.FACEBOOK_CLIENT_ID }}"
          facebookClientSecret="${{ secrets.FACEBOOK_CLIENT_SECRET }}"
          appleClientId="${{ secrets.APPLE_CLIENT_ID }}"
          appleClientSecret="${{ secrets.APPLE_CLIENT_SECRET }}"
          githubToken="${{ secrets.GH_TOKEN }}"
          ' > local.properties
          echo "${{ secrets.FIREBASE_JSON }}" > google-services.json.b64
          base64 -d -i google-services.json.b64 > shared/google-services.json

      - name: Create Google Play Config file
        run: |
          echo "${{ secrets.PLAY_CONFIG_JSON }}" > play_config.json.b64
          base64 -d -i play_config.json.b64 > play_config.json

      - name: Distribute app to Google Play
        run: ./gradlew :shared:publishApk
