name: Code Checks
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:
  checks:
    runs-on: macos-15
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup-gradle
        with:
          gradle-cache-encryption-key: ${{ secrets.GRADLE_CACHE_ENCRYPTION_KEY }}

      - name: Create dummy Firebase json
        run: |
          echo '${{ secrets.FIREBASE_DATABASE_URL }}' > local.properties
          echo 'firebaseAndroidApiKey="${{ secrets.FIREBASE_ANDROID_API_KEY }}"' > local.properties
          echo 'firebaseIosApiKey="${{ secrets.FIREBASE_IOS_API_KEY }}"' > local.properties
          echo 'firebaseGcmSenderId="${{ secrets.FIREBASE_GCM_SENDER_ID }}"' > local.properties
          echo 'firebaseApplicationId="${{ secrets.FIREBASE_APPLICATION_ID }}"' > local.properties
          echo 'firebaseStorageBucket="${{ secrets.FIREBASE_STORAGE_BUCKET }}"' > local.properties
          echo 'firebaseProjectId="${{ secrets.FIREBASE_PROJECT_ID }}"' > local.properties
          echo 'firebaseDatabaseUrl="${{ secrets.FIREBASE_DATABASE_URL }}"' > local.properties

      - name: Run Checks
        run: ./gradlew check

      - name: Upload reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-reports
          path: |
            **/build/reports/*    

  build-android-app:
    name: Build Android App
    runs-on: ubuntu-latest
    needs: [ checks ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup-gradle

      - name: Create dummy Firebase json
        run: |
          echo '${{ secrets.FIREBASE_DATABASE_URL }}' > local.properties
          echo 'firebaseAndroidApiKey="${{ secrets.FIREBASE_ANDROID_API_KEY }}"' > local.properties
          echo 'firebaseIosApiKey="${{ secrets.FIREBASE_IOS_API_KEY }}"' > local.properties
          echo 'firebaseGcmSenderId="${{ secrets.FIREBASE_GCM_SENDER_ID }}"' > local.properties
          echo 'firebaseApplicationId="${{ secrets.FIREBASE_APPLICATION_ID }}"' > local.properties
          echo 'firebaseStorageBucket="${{ secrets.FIREBASE_STORAGE_BUCKET }}"' > local.properties
          echo 'firebaseProjectId="${{ secrets.FIREBASE_PROJECT_ID }}"' > local.properties
          echo 'firebaseDatabaseUrl="${{ secrets.FIREBASE_DATABASE_URL }}"' > local.properties

      - name: Build Android Sample
        run: ./gradlew :androidApp:assembleGooglePlayDebug

  build-desktop-app:
    name: Build Desktop App
    runs-on: ubuntu-latest
    needs: [ checks ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup-gradle

      - name: Build Desktop App
        run: ./gradlew :desktopApp:packageDistributionForCurrentOS

  build-ios-app:
    name: Build iOS App
    runs-on: macos-15
    needs: [ checks ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Xcode version
        run: |
          /usr/bin/xcodebuild -version   

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Xcode version
        run: |
          /usr/bin/xcodebuild -version 

      - name: Setup environment
        uses: ./.github/actions/setup-gradle

      - name: Create Dummy Firebase Plist
        run: |
          echo '${{ secrets.FIREBASE_DATABASE_URL }}' > local.properties
          echo 'firebaseAndroidApiKey="${{ secrets.FIREBASE_ANDROID_API_KEY }}"' > local.properties
          echo 'firebaseIosApiKey="${{ secrets.FIREBASE_IOS_API_KEY }}"' > local.properties
          echo 'firebaseGcmSenderId="${{ secrets.FIREBASE_GCM_SENDER_ID }}"' > local.properties
          echo 'firebaseApplicationId="${{ secrets.FIREBASE_APPLICATION_ID }}"' > local.properties
          echo 'firebaseStorageBucket="${{ secrets.FIREBASE_STORAGE_BUCKET }}"' > local.properties
          echo 'firebaseProjectId="${{ secrets.FIREBASE_PROJECT_ID }}"' > local.properties
          echo 'firebaseDatabaseUrl="${{ secrets.FIREBASE_DATABASE_URL }}"' > local.properties

      - name: Build iOS Sample
        run: |
          cd iosApp
          xcodebuild -configuration Debug -scheme mobi.cwiklinski.bloodline -sdk iphoneos -destination name='iPhone 16 Pro' build | xcbeautify --renderer github-actions
